ansible-test:

1) Integration 

ansible-test network-integration --python 3.12 --inventory /root/ansible_integration_test/ansible-junos-stdlib/ansible_collections/juniper/device/tests/integration/inventory.networking

Issues:
a)
File "/tmp/ansible_ansible.builtin.find_payload_jsp87qb9/ansible_ansible.builtin.find_payload.zip/ansible/module_utils/basic.py", line 5
SyntaxError: future feature annotations is not defined

Fix:
update python interpreter path in inventory.networking.
[all:vars]
ansible_python_interpreter=/root/pyez_ansible_release_validation1/venv/bin/python

b) nNameError: name 'LooseVersion' is not defined
Fix:
pip install LooseVersion

2) Sanity
ansible-test sanity

3) Unit
python3.12 -m pip install pytest
python3.12 -m  pytest 

4) To run specific target
ansible-test network-integration --python 3.12 --inventory /root/pyez_ansible_release_validation1/ansible-junos-stdlib/ansible_collections/juniper/device/tests/integration/inventory.networking --start-at junos_system

PyEZ unit test execution :

python3 -m pip install nose2
python3 -m pip install mock
python3 -m pip install coverage
python3 -m pip install ntc_templates==1.4.1
python3 -m pip install textfsm==0.4.1


nose2 unit tests:
pip install nose2
nose2 -v --coverage jnpr.junos  tests.unit
nose2 --with-coverage -vvv tests.unit

nose2 functional tests:
Functional:
cd tests/functional
cat nose2.cfg 
[unittest]
start-dir=./
nose2 -v -c nose2.cfg



To run the pyez unit tests :
cd py-junos-eznc/tests/unit
nosetests -v --with-coverage --cover-package=jnpr.junos --cover-inclusive -a unit


To run jsnapy unit tests
cd tests/unit
nosetests -v --with-coverage --cover-package=jnpr.jsnapy --cover-inclusive -a unit


To check compilation errors
find . -iname '*.py' | xargs -P4 -I{} python3.7 -Wall -m py_compile {}

To run functional tests

nosetests -v --with-xunit --xunit-file=functionaltests.xml --with-coverage --cover-package=jnpr.junos --cover-xml --cover-inclusive --cover-erase test_config.py test_core.py test_exception.py test_file_ftp.py test_file_scp.py test_route_table.py test_rpc.py test_route_table.py test_shell.py test_table_present.py test_telnet.py test_utils_sw.py


nosetests -v --with-xunit --xunit-file=functionaltests.xml --with-coverage --cover-package=jnpr.junos --cover-xml --cover-inclusive --cover-erase test_utils_file_system

cd /root/pyez/py-junos-eznc/tests/unit

nosetests -v *


UT/FT execution on windows:

tests\unit

nosetests.exe  -v .\test_check.py

 Nosetest debugging:
 
 To set breakpoints 
 from nose.tools import set_trace; set_trace()
 
 
 /root/sw_install_member/py-junos-eznc/tests/unit/utils
 nosetests  -v ./test_sw.py:TestSW
 
 
Python3.10:

AttributeError: module 'collections' has no attribute 'Callable'
pip uninstall -y nose
pip install -U nose --no-binary :all:
https://github.com/nose-devs/nose/issues/1099

nose2:

nose2 tests:
python3 -m pip install nose2

nose2 -v --coverage jnpr.junos --with-coverage
nose2 -v --coverage jnpr.junos 
python3 -m pip install nose2[coverage_plugin]



To run functional tests:
(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# cat nose2.cfg 
[unittest]
start-dir=./
(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# nose2 -v -c nose2.cfg
(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# cat tests/functional/nose2.cfg 
[unittest]
start-dir=./


(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# cat nose2.cfg 
[unittest]
start-dir=./tests/functional
(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# ls tests/functional/
config.yaml          protocol_data.yml  test_config.py      test_file_scp.py     test_sshConfigure.py       test_utils_sw.py
coverage.xml         protocol_temp.j2   test_core.py        test_route_table.py  test_table_present.py
functionaltests.xml  __pycache__        test_device_ssh.py  test_rpc.py          test_table.py
__init__.py          random             test_exception.py   test.sh              test_telnet.py
nose2.cfg            skip_version.py    test_file_ftp.py    test_shell.py        test_utils_file_system.py


/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/subprocess.py:935: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdin = io.open(p2cwrite, 'wb', bufsize)
https://github.com/yadage/packtivity/pull/78/files

Fix for Unit test faliures:

Fix1:
python3 -m pip install ntc_templates==1.4.1
python3 -m pip install textfsm==0.4.1

Fix2:
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html





inventory_junos:

[junos]
xx.xx.xx.xx

[junos:vars]
ansible_network_os=juniper.device.junos
ansible_ssh_user=
ansible_ssh_pass=
ansible_connection=ansible.netcommon.netconf

[all:vars]
ansible_python_interpreter=/root/ansible_modules_redirection_ansible_merger_branch_venv/venv/bin/python3



inventory_network_cli:


[junos]
xx.xx.xx.xx
 
# WORKING SETUP
[junos:vars]
 
ansible_network_os=juniper.device.junos
ansible_ssh_user=ansible_user1
ansible_ssh_pass=ansible123
ansible_connection=ansible.netcommon.network_cli

[all:vars]
ansible_python_interpreter=/usr/bin/python3


find ./ -type f -exec sed -i 's/junos_device/all/gI' {} \;
